### ISSUE TITLE
Add some github tags to this repo for discoverability

### ISSUE THREAD

**Issue by dontlaugh** [ProtonMail/go-appdir#6]
Nice project! But discoverability might be aided with some repo-level tags. I was halfway down the path of rolling my own solution when I randomly saw this library on the arch wiki:

https://wiki.archlinux.org/index.php/XDG_Base_Directory#Libraries

Some suggested tags: `xdg`, `cache`, `cross-platform`, etc.

**Comment by emersion** [comment]
Added a bunch of tags. Glad you like this library :)
